# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180204_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
